# Generated by Django 3.0.6 on 2020-06-15 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HirePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address_line1', models.CharField(default='', max_length=100)),
                ('address_line2', models.CharField(default='', max_length=100)),
                ('address_line3', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('rent_price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='Pictures')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('hire_point', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicles.HirePoint')),
                ('manufacturer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicles.Manufacturer')),
                ('vehicle_line', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehicles.VehicleLine')),
            ],
        ),
    ]
