# Generated by Django 3.0.6 on 2020-06-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Pictures')),
                ('productVendor', models.CharField(default='', max_length=100)),
                ('rentPrice', models.IntegerField(default=0)),
                ('rate', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
