# Generated by Django 3.0.6 on 2020-05-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='priceEach',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantityOrdered',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart'),
        ),
    ]
