# Generated by Django 3.0.5 on 2020-05-12 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shipping', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('totalPrice', models.IntegerField(default=0)),
                ('is_rented', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
        ),
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('requiredDate', models.DateTimeField(blank=True, null=True)),
                ('shippedDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orders')),
            ],
        ),
    ]
